----------------------------------------------------------------------
Ran 21 tests in 0.059s

OK
Traceback (most recent call last):
  File "C:/Python32/RightTestXML", line 262, in <module>
    unittest.main()
  File "C:\Python32\lib\unittest\main.py", line 124, in __init__
    self.runTests()
  File "C:\Python32\lib\unittest\main.py", line 272, in runTests
    sys.exit(not self.result.wasSuccessful())
SystemExit: False
